LANGUAGES = {
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "nl": "Dutch",
    "ru": "Russian",
    "pt": "Portuguese",
    "zh": "Chinese Simplified",
    "zh-Hant": "Chinese Traditional",
    "ja": "Japanese",
    "ko": "Korean",
    "tr": "Turkish",
}
